/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

/**
 *
 * @author Tamanna
 */
public class CorpseInfoPageForPermanent extends javax.swing.JFrame {

    /**
     * Creates new form CorpseInfoPageForPermanent
     */
    public CorpseInfoPageForPermanent() {
        initComponents();
    }
    
   public CorpseInfoPageForPermanent(String plotNumber,String corpseName,String father, String mother,String birth,
            String Nid,String cause,String time, String owner_id, String owner_name, String owner_nid,String owner_contact,
            String owner_relation,String owner_address,String birth_date,String death_date,String size,String Gender,
            String Fee,String burried,String recycle){
        
        initComponents();
        plotNo.setText(plotNumber);
        name.setText(corpseName);
        fatherName.setText(father);
        motherName.setText(mother);
        BirthCertificate.setText(birth);
        nid.setText(Nid);
        causeOfDeath.setText(cause);
        timeOfDeath.setText(time);
        ownerId.setText(owner_id);
        ownerName.setText(owner_name);
        ownerNid.setText(owner_nid);
        ownerContactNo.setText(owner_contact);
        ownerRelation.setText(owner_relation);
        ownerAddress.setText(owner_address);
        dateOfBirth.setText(birth_date);
        dateOfDeath.setText(death_date);
        plotSize.setText(size);
        gender.setText(Gender);
        fee.setText(Fee);
        burriedDate.setText(burried);
        recycleDate.setText(recycle);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CorpseInfo = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        plotNo = new javax.swing.JTextField();
        motherName = new javax.swing.JTextField();
        causeOfDeath = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        ownerAddress = new javax.swing.JTextField();
        ownerName = new javax.swing.JTextField();
        ownerId = new javax.swing.JTextField();
        BirthCertificate = new javax.swing.JTextField();
        nid = new javax.swing.JTextField();
        fatherName = new javax.swing.JTextField();
        dateOfBirth = new javax.swing.JTextField();
        ownerContactNo = new javax.swing.JTextField();
        ownerNid = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        timeOfDeath = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        gender = new javax.swing.JTextField();
        dateOfDeath = new javax.swing.JTextField();
        ownerRelation = new javax.swing.JTextField();
        plotSize = new javax.swing.JTextField();
        fee = new javax.swing.JTextField();
        recycleDate = new javax.swing.JTextField();
        burriedDate = new javax.swing.JTextField();
        jLabel86 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CorpseInfo.setBackground(new java.awt.Color(51, 51, 51));

        jLabel61.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(255, 255, 255));
        jLabel61.setText("Plot No:");

        jLabel63.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("Plot Size:");

        jLabel64.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Time of Death: ");

        jLabel65.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("Cause of Death:");

        jLabel66.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("Name:");

        jLabel67.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(255, 255, 255));
        jLabel67.setText("Gender:");

        jLabel68.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68.setText("Father Name:");

        jLabel69.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69.setText("Mother Name:");

        jLabel70.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70.setText("Date of Birth:");

        jLabel71.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Date of Death:");

        jLabel72.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72.setText("NID:");

        jLabel74.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Birth Certificate:");

        jLabel76.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("Owner Id:");

        jLabel77.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("Owner Name:");

        jLabel78.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setText("Owner Relation: ");

        jLabel79.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("Owner Contact No:");

        jLabel80.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Owner NID:");

        jLabel81.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(255, 255, 255));
        jLabel81.setText("Owner Address: ");

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("Information of Corpse");

        plotNo.setBackground(new java.awt.Color(102, 102, 102));
        plotNo.setForeground(new java.awt.Color(255, 255, 255));
        plotNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        motherName.setBackground(new java.awt.Color(102, 102, 102));
        motherName.setForeground(new java.awt.Color(255, 255, 255));
        motherName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        causeOfDeath.setBackground(new java.awt.Color(102, 102, 102));
        causeOfDeath.setForeground(new java.awt.Color(255, 255, 255));
        causeOfDeath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        name.setBackground(new java.awt.Color(102, 102, 102));
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        ownerAddress.setBackground(new java.awt.Color(102, 102, 102));
        ownerAddress.setForeground(new java.awt.Color(255, 255, 255));
        ownerAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        ownerName.setBackground(new java.awt.Color(102, 102, 102));
        ownerName.setForeground(new java.awt.Color(255, 255, 255));
        ownerName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        ownerId.setBackground(new java.awt.Color(102, 102, 102));
        ownerId.setForeground(new java.awt.Color(255, 255, 255));
        ownerId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        BirthCertificate.setBackground(new java.awt.Color(102, 102, 102));
        BirthCertificate.setForeground(new java.awt.Color(255, 255, 255));
        BirthCertificate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        nid.setBackground(new java.awt.Color(102, 102, 102));
        nid.setForeground(new java.awt.Color(255, 255, 255));
        nid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        fatherName.setBackground(new java.awt.Color(102, 102, 102));
        fatherName.setForeground(new java.awt.Color(255, 255, 255));
        fatherName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        dateOfBirth.setBackground(new java.awt.Color(102, 102, 102));
        dateOfBirth.setForeground(new java.awt.Color(255, 255, 255));
        dateOfBirth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        ownerContactNo.setBackground(new java.awt.Color(102, 102, 102));
        ownerContactNo.setForeground(new java.awt.Color(255, 255, 255));
        ownerContactNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        ownerNid.setBackground(new java.awt.Color(102, 102, 102));
        ownerNid.setForeground(new java.awt.Color(255, 255, 255));
        ownerNid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        next.setBackground(new java.awt.Color(102, 102, 102));
        next.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Finish");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        timeOfDeath.setBackground(new java.awt.Color(102, 102, 102));
        timeOfDeath.setForeground(new java.awt.Color(255, 255, 255));
        timeOfDeath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        timeOfDeath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeOfDeathActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(102, 102, 102));
        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        gender.setBackground(new java.awt.Color(102, 102, 102));
        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        dateOfDeath.setBackground(new java.awt.Color(102, 102, 102));
        dateOfDeath.setForeground(new java.awt.Color(255, 255, 255));
        dateOfDeath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        ownerRelation.setBackground(new java.awt.Color(102, 102, 102));
        ownerRelation.setForeground(new java.awt.Color(255, 255, 255));
        ownerRelation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        plotSize.setBackground(new java.awt.Color(102, 102, 102));
        plotSize.setForeground(new java.awt.Color(255, 255, 255));
        plotSize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        fee.setBackground(new java.awt.Color(102, 102, 102));
        fee.setForeground(new java.awt.Color(255, 255, 255));
        fee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        recycleDate.setBackground(new java.awt.Color(102, 102, 102));
        recycleDate.setForeground(new java.awt.Color(255, 255, 255));
        recycleDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        burriedDate.setBackground(new java.awt.Color(102, 102, 102));
        burriedDate.setForeground(new java.awt.Color(255, 255, 255));
        burriedDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel86.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(255, 255, 255));
        jLabel86.setText("Fee :");

        jLabel75.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Recycle Date:");

        jLabel73.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setText("Burried Date: ");

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("Booking Information");

        javax.swing.GroupLayout CorpseInfoLayout = new javax.swing.GroupLayout(CorpseInfo);
        CorpseInfo.setLayout(CorpseInfoLayout);
        CorpseInfoLayout.setHorizontalGroup(
            CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CorpseInfoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel84)
                .addGap(440, 440, 440))
            .addGroup(CorpseInfoLayout.createSequentialGroup()
                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CorpseInfoLayout.createSequentialGroup()
                        .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CorpseInfoLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel76)
                                    .addComponent(jLabel74)
                                    .addComponent(jLabel68)
                                    .addComponent(jLabel61))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CorpseInfoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel81)
                                .addGap(18, 18, 18)))
                        .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BirthCertificate, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(plotNo)
                            .addComponent(fatherName)
                            .addComponent(ownerId)
                            .addComponent(ownerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CorpseInfoLayout.createSequentialGroup()
                                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel77)
                                    .addComponent(jLabel78)
                                    .addComponent(jLabel73)
                                    .addComponent(jLabel75))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ownerName, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(ownerRelation)
                                    .addComponent(burriedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(recycleDate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CorpseInfoLayout.createSequentialGroup()
                                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel67)
                                    .addComponent(jLabel63)
                                    .addComponent(jLabel69))
                                .addGap(23, 23, 23)
                                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gender)
                                    .addComponent(motherName)
                                    .addComponent(plotSize))))
                        .addGap(55, 55, 55)
                        .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CorpseInfoLayout.createSequentialGroup()
                                .addComponent(jLabel71)
                                .addGap(12, 12, 12)
                                .addComponent(dateOfDeath, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel64))
                            .addGroup(CorpseInfoLayout.createSequentialGroup()
                                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(CorpseInfoLayout.createSequentialGroup()
                                        .addComponent(jLabel66)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CorpseInfoLayout.createSequentialGroup()
                                        .addComponent(jLabel72)
                                        .addGap(81, 81, 81)
                                        .addComponent(nid, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel70)
                                    .addComponent(jLabel65)))
                            .addGroup(CorpseInfoLayout.createSequentialGroup()
                                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(CorpseInfoLayout.createSequentialGroup()
                                        .addComponent(jLabel86)
                                        .addGap(27, 27, 27)
                                        .addComponent(fee, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(CorpseInfoLayout.createSequentialGroup()
                                        .addComponent(jLabel80)
                                        .addGap(34, 34, 34)
                                        .addComponent(ownerNid, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel79)))
                        .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeOfDeath, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ownerContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(causeOfDeath, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CorpseInfoLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CorpseInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CorpseInfoLayout.createSequentialGroup()
                                .addComponent(jLabel83)
                                .addGap(379, 379, 379)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        CorpseInfoLayout.setVerticalGroup(
            CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CorpseInfoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel83)
                .addGap(59, 59, 59)
                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel74)
                        .addComponent(BirthCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CorpseInfoLayout.createSequentialGroup()
                        .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(CorpseInfoLayout.createSequentialGroup()
                                .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(causeOfDeath, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel71)
                                    .addComponent(dateOfDeath, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel64)
                                    .addComponent(timeOfDeath, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CorpseInfoLayout.createSequentialGroup()
                                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CorpseInfoLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel61))
                                    .addGroup(CorpseInfoLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel63)
                                            .addComponent(plotNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel66)
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel70))
                                    .addComponent(plotSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CorpseInfoLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel68)
                                            .addComponent(fatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel69)))
                                    .addGroup(CorpseInfoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(motherName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel72)))
                                    .addGroup(CorpseInfoLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel65)
                                            .addComponent(nid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel67)
                                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(1, 1, 1)))
                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CorpseInfoLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel79)
                            .addComponent(ownerContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ownerNid, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel80)))
                    .addGroup(CorpseInfoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ownerId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel77)
                                .addComponent(ownerName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel76))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel81)
                            .addComponent(ownerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel78)
                            .addComponent(ownerRelation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CorpseInfoLayout.createSequentialGroup()
                        .addComponent(jLabel75)
                        .addGap(18, 18, 18)
                        .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(back)
                            .addComponent(next))
                        .addGap(38, 38, 38))
                    .addGroup(CorpseInfoLayout.createSequentialGroup()
                        .addComponent(jLabel84)
                        .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CorpseInfoLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel73)
                                    .addComponent(burriedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CorpseInfoLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(CorpseInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fee, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel86))))
                        .addGap(5, 5, 5)
                        .addComponent(recycleDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CorpseInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CorpseInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        Permanent_CorpseInfo mm = new Permanent_CorpseInfo();
        mm.setVisible(true);
        
    }//GEN-LAST:event_backActionPerformed

    private void timeOfDeathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeOfDeathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeOfDeathActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
            System.exit(0);
     
       
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CorpseInfoPageForPermanent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CorpseInfoPageForPermanent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CorpseInfoPageForPermanent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CorpseInfoPageForPermanent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CorpseInfoPageForPermanent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BirthCertificate;
    private javax.swing.JPanel CorpseInfo;
    private javax.swing.JButton back;
    private javax.swing.JTextField burriedDate;
    private javax.swing.JTextField causeOfDeath;
    private javax.swing.JTextField dateOfBirth;
    private javax.swing.JTextField dateOfDeath;
    private javax.swing.JTextField fatherName;
    private javax.swing.JTextField fee;
    private javax.swing.JTextField gender;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JTextField motherName;
    private javax.swing.JTextField name;
    private javax.swing.JButton next;
    private javax.swing.JTextField nid;
    private javax.swing.JTextField ownerAddress;
    private javax.swing.JTextField ownerContactNo;
    private javax.swing.JTextField ownerId;
    private javax.swing.JTextField ownerName;
    private javax.swing.JTextField ownerNid;
    private javax.swing.JTextField ownerRelation;
    private javax.swing.JTextField plotNo;
    private javax.swing.JTextField plotSize;
    private javax.swing.JTextField recycleDate;
    private javax.swing.JTextField timeOfDeath;
    // End of variables declaration//GEN-END:variables
}
