
package Form;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/**
 *
 * @author Tamanna
 */
public class date extends javax.swing.JFrame {

    /**
     * Creates new form date
     */
    public date() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        today = new com.toedter.calendar.JDateChooser();
        nextday = new com.toedter.calendar.JDateChooser();
        generate = new javax.swing.JButton();
        next = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        today.setDateFormatString("yyyy-MM-dd");
        today.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                todayAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        today.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                todayMouseWheelMoved(evt);
            }
        });
        today.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                todayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                todayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                todayMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                todayMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                todayMouseReleased(evt);
            }
        });
        today.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                todayInputMethodTextChanged(evt);
            }
        });
        today.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                todayPropertyChange(evt);
            }
        });

        nextday.setDateFormatString("yyyy-MM-dd");
        nextday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextdayMouseClicked(evt);
            }
        });

        generate.setText("generate");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nextday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(today, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(generate)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(today, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generate))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
      SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date bdate = today.getDate();
            java.util.Calendar c = java.util.Calendar.getInstance();
            c.add(java.util.Calendar.DATE, 1095);

             String dd = sdf.format(c.getTime());
             next.setText(dd);
             String date = "13 Oct 2016";
             Date date2 = c.getTime();
             nextday.setDate(date2);
             System.out.println("7 days later: " + c.getTime());
    }//GEN-LAST:event_generateActionPerformed

    private void nextdayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextdayMouseClicked
      
    }//GEN-LAST:event_nextdayMouseClicked

    private void todayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todayMouseClicked
     
    }//GEN-LAST:event_todayMouseClicked

    private void todayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todayMousePressed
      
    }//GEN-LAST:event_todayMousePressed

    private void todayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todayMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_todayMouseReleased

    private void todayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todayMouseExited
       
    }//GEN-LAST:event_todayMouseExited

    private void todayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_todayMouseEntered
        
    }//GEN-LAST:event_todayMouseEntered

    private void todayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_todayPropertyChange
        
             
    }//GEN-LAST:event_todayPropertyChange

    private void todayMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_todayMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_todayMouseWheelMoved

    private void todayInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_todayInputMethodTextChanged
       
    }//GEN-LAST:event_todayInputMethodTextChanged

    private void todayAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_todayAncestorAdded
      SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date bdate = today.getDate();
            java.util.Calendar c = java.util.Calendar.getInstance();
            c.add(java.util.Calendar.DATE, 1095);

             String dd = sdf.format(c.getTime());
             next.setText(dd);
             Date date2 = c.getTime();
             nextday.setDate(date2);
    }//GEN-LAST:event_todayAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(date.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new date().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generate;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField next;
    private com.toedter.calendar.JDateChooser nextday;
    private com.toedter.calendar.JDateChooser today;
    // End of variables declaration//GEN-END:variables
}
